
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author spook
 */
public class besebes extends javax.swing.JFrame {

    /**
     * Creates new form besebes
     */
    public besebes() {
        initComponents();
        Seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        y13 = new javax.swing.JTextField();
        z11 = new javax.swing.JTextField();
        w11 = new javax.swing.JTextField();
        aMatrisi = new javax.swing.JLabel();
        w12 = new javax.swing.JTextField();
        z12 = new javax.swing.JTextField();
        w13 = new javax.swing.JTextField();
        z13 = new javax.swing.JTextField();
        w14 = new javax.swing.JTextField();
        x12 = new javax.swing.JTextField();
        x14 = new javax.swing.JTextField();
        x13 = new javax.swing.JTextField();
        y14 = new javax.swing.JTextField();
        y11 = new javax.swing.JTextField();
        y12 = new javax.swing.JTextField();
        x11 = new javax.swing.JTextField();
        z14 = new javax.swing.JTextField();
        q11 = new javax.swing.JTextField();
        q12 = new javax.swing.JTextField();
        q13 = new javax.swing.JTextField();
        q14 = new javax.swing.JTextField();
        z15 = new javax.swing.JTextField();
        w15 = new javax.swing.JTextField();
        q15 = new javax.swing.JTextField();
        x15 = new javax.swing.JTextField();
        y15 = new javax.swing.JTextField();
        hesapla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        matrixsonuc = new javax.swing.JLabel();
        matrixA = new javax.swing.JRadioButton();
        e14 = new javax.swing.JTextField();
        c15 = new javax.swing.JTextField();
        d15 = new javax.swing.JTextField();
        e15 = new javax.swing.JTextField();
        a15 = new javax.swing.JTextField();
        b15 = new javax.swing.JTextField();
        d14 = new javax.swing.JTextField();
        a12 = new javax.swing.JTextField();
        a14 = new javax.swing.JTextField();
        a13 = new javax.swing.JTextField();
        b14 = new javax.swing.JTextField();
        b11 = new javax.swing.JTextField();
        b12 = new javax.swing.JTextField();
        a11 = new javax.swing.JTextField();
        c14 = new javax.swing.JTextField();
        e11 = new javax.swing.JTextField();
        b13 = new javax.swing.JTextField();
        c11 = new javax.swing.JTextField();
        d11 = new javax.swing.JTextField();
        bMatrisi = new javax.swing.JLabel();
        d12 = new javax.swing.JTextField();
        c12 = new javax.swing.JTextField();
        d13 = new javax.swing.JTextField();
        c13 = new javax.swing.JTextField();
        e12 = new javax.swing.JTextField();
        e13 = new javax.swing.JTextField();
        matrixB = new javax.swing.JRadioButton();
        g1 = new javax.swing.JLabel();
        g2 = new javax.swing.JLabel();
        g3 = new javax.swing.JLabel();
        g5 = new javax.swing.JLabel();
        g6 = new javax.swing.JLabel();
        g7 = new javax.swing.JLabel();
        g9 = new javax.swing.JLabel();
        g10 = new javax.swing.JLabel();
        g11 = new javax.swing.JLabel();
        g4 = new javax.swing.JLabel();
        g8 = new javax.swing.JLabel();
        g12 = new javax.swing.JLabel();
        g13 = new javax.swing.JLabel();
        g14 = new javax.swing.JLabel();
        g15 = new javax.swing.JLabel();
        g16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        g17 = new javax.swing.JLabel();
        g18 = new javax.swing.JLabel();
        g19 = new javax.swing.JLabel();
        g20 = new javax.swing.JLabel();
        g21 = new javax.swing.JLabel();
        g22 = new javax.swing.JLabel();
        g23 = new javax.swing.JLabel();
        g24 = new javax.swing.JLabel();
        g25 = new javax.swing.JLabel();
        transpozA = new javax.swing.JRadioButton();
        transpozB = new javax.swing.JRadioButton();
        cikarma = new javax.swing.JRadioButton();
        toplama = new javax.swing.JRadioButton();
        temizle = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("5x5 Matrix Hesaplama");

        y13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        z11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        w11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        aMatrisi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aMatrisi.setText("A Matrisi");

        w12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        z12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        w13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        z13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        w14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        x12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        x14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        x13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        y14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        y11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        y12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        x11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        z14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        q11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        q12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        q13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        q14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        z15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        w15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        q15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        x15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        y15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        hesapla.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hesapla.setText("Hesapla");
        hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesaplaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Det Sonucu : ");

        buttonGroup1.add(matrixA);
        matrixA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        matrixA.setText("A Determinant");

        e14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        c15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        d15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        e15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        a15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        b15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        d14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        a12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        a14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        a13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        b14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        b11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        b12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        a11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        c14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        e11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        b13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        c11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        d11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        bMatrisi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bMatrisi.setText("B Matrisi");

        d12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        c12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        d13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        c13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        e12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        e13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z13KeyTyped(evt);
            }
        });

        buttonGroup1.add(matrixB);
        matrixB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        matrixB.setText("B Determinant");

        g1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g1.setText("*");

        g2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g2.setText("*");

        g3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g3.setText("*");

        g5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g5.setText("*");

        g6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g6.setText("*");

        g7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g7.setText("*");

        g9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g9.setText("*");

        g10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g10.setText("*");

        g11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g11.setText("*");

        g4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g4.setText("*");

        g8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g8.setText("*");

        g12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g12.setText("*");

        g13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g13.setText("*");

        g14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g14.setText("*");

        g15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g15.setText("*");

        g16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g16.setText("*");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Matris Sonuç:");

        g17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g17.setText("*");

        g18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g18.setText("*");

        g19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g19.setText("*");

        g20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g20.setText("*");

        g21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g21.setText("*");

        g22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g22.setText("*");

        g23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g23.setText("*");

        g24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g24.setText("*");

        g25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g25.setText("*");

        buttonGroup1.add(transpozA);
        transpozA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transpozA.setText("A Transpoz ");
        transpozA.setVerifyInputWhenFocusTarget(false);

        buttonGroup1.add(transpozB);
        transpozB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transpozB.setText("B Transpoz ");
        transpozB.setVerifyInputWhenFocusTarget(false);

        buttonGroup1.add(cikarma);
        cikarma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cikarma.setText("A - B işlemi");
        cikarma.setVerifyInputWhenFocusTarget(false);

        buttonGroup1.add(toplama);
        toplama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        toplama.setText("A + B işlemi");
        toplama.setVerifyInputWhenFocusTarget(false);

        temizle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        temizle.setText("Temizle");
        temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Kaydet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Matris Hesaplama");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jMenuItem1.setText("3x3 Matris Hesaplama");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jMenuItem2.setText("4x4 Matris Hesaplama");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Çıkış");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(aMatrisi)
                .addGap(182, 182, 182)
                .addComponent(bMatrisi)
                .addGap(389, 389, 389))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(g3)
                                        .addGap(18, 18, 18)
                                        .addComponent(g8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(179, 179, 179)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(g2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(g5)
                                                .addComponent(g4))
                                            .addComponent(g1, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                    .addComponent(g6)
                                                    .addComponent(g7)
                                                    .addComponent(g9)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(g10)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(g11)
                                    .addComponent(g12)
                                    .addComponent(g13)
                                    .addComponent(g14)
                                    .addComponent(g15))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(g16)
                                    .addComponent(g17)
                                    .addComponent(g18)
                                    .addComponent(g19)
                                    .addComponent(g20))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(g25)
                                    .addComponent(g21)
                                    .addComponent(g22)
                                    .addComponent(g23)
                                    .addComponent(g24)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(w15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(y15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(z15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(x15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matrixB)
                            .addComponent(matrixA)
                            .addComponent(transpozA)
                            .addComponent(cikarma)
                            .addComponent(transpozB)
                            .addComponent(toplama))))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(q11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(q12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(q13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(q14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(w11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(w12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(w13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(y11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(y12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(y13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(z11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(z12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(z13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(x11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(x12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(x13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(w14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(y14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(z14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(x14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hesapla)
                                .addGap(80, 80, 80)))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(e11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(e12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(e13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(e14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(d11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(d12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(d13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(c12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(c13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(a11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(a13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(b14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(c14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(a14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(e15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(b15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(c15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(temizle)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(matrixsonuc)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aMatrisi)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(x11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(x12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(x13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(y11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(z11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(z13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(z12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(x14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(y14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(z14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(x15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(y15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(z15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(w11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(w13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(w12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(w14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(q11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(q13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(q12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(q14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(w15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bMatrisi)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(a11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(a13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(c13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(c12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(a14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(c14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(d11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(d13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(d12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(d14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(e11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(e13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(e12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(e14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(g11)
                                        .addGap(106, 106, 106))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(g1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(g2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(g3)
                                                            .addComponent(g8)
                                                            .addComponent(g13))
                                                        .addGap(1, 1, 1)
                                                        .addComponent(g4))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(19, 19, 19)
                                                        .addComponent(jLabel2))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(g6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(g7)
                                                    .addComponent(g12))
                                                .addGap(36, 36, 36)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(g9)
                                                    .addComponent(g14))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g5)
                                    .addComponent(g10)
                                    .addComponent(g15)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(g16)
                                            .addGap(106, 106, 106))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(70, 70, 70)
                                                    .addComponent(g18))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(35, 35, 35)
                                                    .addComponent(g17)
                                                    .addGap(36, 36, 36)
                                                    .addComponent(g19)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addComponent(g20))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(g22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g23))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(g21)
                                    .addGap(71, 71, 71)
                                    .addComponent(g24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g25)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(matrixA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrixB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transpozA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transpozB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cikarma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toplama)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temizle)
                    .addComponent(hesapla)
                    .addComponent(jLabel1)
                    .addComponent(matrixsonuc)
                    .addComponent(jButton1))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesaplaActionPerformed
        if(matrixA.isSelected()==true){
            int s11 = Integer.parseInt(x11.getText());
            int s12 = Integer.parseInt(x12.getText());
            int s13 = Integer.parseInt(x13.getText());
            int s14 = Integer.parseInt(x14.getText());
            int s15 = Integer.parseInt(x15.getText());
            int s21 = Integer.parseInt(y11.getText());
            int s22 = Integer.parseInt(y12.getText());
            int s23 = Integer.parseInt(y13.getText());
            int s24 = Integer.parseInt(y14.getText());
            int s25 = Integer.parseInt(y15.getText());
            int s31 = Integer.parseInt(z11.getText());
            int s32 = Integer.parseInt(z12.getText());
            int s33 = Integer.parseInt(z13.getText());
            int s34 = Integer.parseInt(z14.getText());
            int s35 = Integer.parseInt(z15.getText());
            int s41 = Integer.parseInt(w11.getText());
            int s42 = Integer.parseInt(w12.getText());
            int s43 = Integer.parseInt(w13.getText());
            int s44 = Integer.parseInt(w14.getText());
            int s45 = Integer.parseInt(w15.getText());
            int s51 = Integer.parseInt(q11.getText());
            int s52 = Integer.parseInt(q12.getText());
            int s53 = Integer.parseInt(q13.getText());
            int s54 = Integer.parseInt(q14.getText());
            int s55 = Integer.parseInt(q15.getText());
            int d11 =(s22*s33*s44*s55)+(s42*s53*s24*s35)+(s25*s34*s43*s52)+(s45*s54*s23*s32)-
            (s32*s43*s54*s25)-(s52*s23*s34*s45)-(s35*s44*s53*s22)-(s55*s24*s33*s42);
            int d12 =(s32*s44*s53*s25)+(s52*s24*s33*s45)+(s35*s43*s54*s22)+(s55*s23*s34*s42)-
            (s22*s34*s43*s55)-(s42*s54*s23*s35)-(s25*s33*s44*s52)-(s45*s53*s24*s32);
            int d13 =(s32*s43*s55*s24)+(s52*s23*s35*s44)+(s34*s45*s53*s22)+(s54*s25*s33*s42)-
            (s22*s33*s45*s54)-(s42*s53*s25*s34)-(s24*s35*s43*s52)-(s44*s55*s23*s32);
            int d21 =(s21*s33*s44*s55)+(s41*s53*s24*s35)+(s25*s34*s43*s51)+(s45*s54*s23*s31)-
            (s31*s43*s54*s25)-(s51*s23*s34*s45)-(s35*s44*s53*s21)-(s55*s24*s33*s41);
            int d22 =(s31*s44*s53*s25)+(s51*s24*s33*s45)+(s35*s43*s54*s21)+(s55*s23*s34*s41)-
            (s21*s34*s43*s55)-(s41*s54*s23*s35)-(s25*s33*s44*s51)-(s45*s53*s24*s31);
            int d23 =(s31*s43*s55*s24)+(s51*s23*s35*s44)+(s34*s45*s53*s21)+(s54*s25*s33*s41)-
            (s21*s33*s45*s54)-(s41*s53*s25*s34)-(s24*s35*s43*s51)-(s44*s55*s23*s31);
            int d31 =(s21*s32*s44*s55)+(s41*s52*s24*s35)+(s25*s34*s42*s51)+(s45*s54*s22*s31)-
            (s31*s42*s54*s25)-(s51*s22*s34*s45)-(s35*s44*s52*s21)-(s55*s24*s32*s41);
            int d32 =(s31*s44*s52*s25)+(s51*s24*s32*s45)+(s35*s42*s54*s21)+(s55*s22*s34*s41)-
            (s21*s34*s42*s55)-(s41*s54*s22*s35)-(s25*s32*s44*s51)-(s45*s52*s24*s31);
            int d33 =(s31*s42*s55*s24)+(s51*s22*s35*s44)+(s34*s45*s52*s21)+(s54*s25*s32*s41)-
            (s21*s32*s45*s54)-(s41*s52*s25*s34)-(s24*s35*s42*s51)-(s44*s55*s22*s31);
            int d41 =(s21*s32*s43*s55)+(s41*s52*s23*s35)+(s25*s33*s42*s51)+(s45*s53*s22*s31)-
            (s31*s42*s53*s25)-(s51*s22*s33*s45)-(s35*s43*s52*s21)-(s55*s23*s32*s41);
            int d42 =(s31*s43*s52*s25)+(s51*s23*s32*s45)+(s35*s42*s53*s21)+(s55*s22*s33*s41)-
            (s21*s33*s42*s55)-(s41*s53*s22*s35)-(s25*s32*s43*s51)-(s45*s52*s23*s31);
            int d43 =(s31*s42*s55*s23)+(s51*s22*s35*s43)+(s33*s45*s52*s21)+(s53*s25*s32*s41)-
            (s21*s32*s45*s53)-(s41*s52*s25*s33)-(s23*s35*s42*s51)-(s43*s55*s22*s31);
            int d51 =(s21*s32*s43*s54)+(s41*s52*s23*s34)+(s24*s33*s42*s51)+(s44*s53*s22*s31)-
            (s31*s42*s53*s24)-(s51*s22*s33*s44)-(s34*s43*s52*s21)-(s54*s23*s32*s41);
            int d52 =(s31*s43*s52*s24)+(s51*s23*s32*s44)+(s34*s42*s53*s21)+(s54*s22*s33*s41)-
            (s21*s33*s42*s54)-(s41*s53*s22*s34)-(s24*s32*s43*s51)-(s44*s52*s23*s31);
            int d53 =(s31*s42*s54*s23)+(s51*s22*s34*s43)+(s33*s44*s52*s21)+(s53*s24*s32*s41)-
            (s21*s32*s44*s53)-(s41*s52*s24*s33)-(s23*s34*s42*s51)-(s43*s54*s22*s31);
            int detA11sonuc=d11+d12+d13;
            int detA12sonuc=d21+d22+d23;
            int detA13sonuc=d31+d32+d33;
            int detA14sonuc=d41+d42+d43;
            int detA15sonuc=d51+d52+d53;
            int anaSonuc = (s11*detA11sonuc)+((-s12)*detA12sonuc)+(s13*detA13sonuc)+((-s14)*detA14sonuc)+(s15*detA15sonuc);
            matrixsonuc.setText(Integer.toString(anaSonuc));
        }
        else if(matrixB.isSelected()==true){
            int s11 = Integer.parseInt(a11.getText());
            int s12 = Integer.parseInt(a12.getText());
            int s13 = Integer.parseInt(a13.getText());
            int s14 = Integer.parseInt(a14.getText());
            int s15 = Integer.parseInt(a15.getText());
            int s21 = Integer.parseInt(b11.getText());
            int s22 = Integer.parseInt(b12.getText());
            int s23 = Integer.parseInt(b13.getText());
            int s24 = Integer.parseInt(b14.getText());
            int s25 = Integer.parseInt(b15.getText());
            int s31 = Integer.parseInt(c11.getText());
            int s32 = Integer.parseInt(c12.getText());
            int s33 = Integer.parseInt(c13.getText());
            int s34 = Integer.parseInt(c14.getText());
            int s35 = Integer.parseInt(c15.getText());
            int s41 = Integer.parseInt(d11.getText());
            int s42 = Integer.parseInt(d12.getText());
            int s43 = Integer.parseInt(d13.getText());
            int s44 = Integer.parseInt(d14.getText());
            int s45 = Integer.parseInt(d15.getText());
            int s51 = Integer.parseInt(e11.getText());
            int s52 = Integer.parseInt(e12.getText());
            int s53 = Integer.parseInt(e13.getText());
            int s54 = Integer.parseInt(e14.getText());
            int s55 = Integer.parseInt(e15.getText());
            int d11 =(s22*s33*s44*s55)+(s42*s53*s24*s35)+(s25*s34*s43*s52)+(s45*s54*s23*s32)-
            (s32*s43*s54*s25)-(s52*s23*s34*s45)-(s35*s44*s53*s22)-(s55*s24*s33*s42);
            int d12 =(s32*s44*s53*s25)+(s52*s24*s33*s45)+(s35*s43*s54*s22)+(s55*s23*s34*s42)-
            (s22*s34*s43*s55)-(s42*s54*s23*s35)-(s25*s33*s44*s52)-(s45*s53*s24*s32);
            int d13 =(s32*s43*s55*s24)+(s52*s23*s35*s44)+(s34*s45*s53*s22)+(s54*s25*s33*s42)-
            (s22*s33*s45*s54)-(s42*s53*s25*s34)-(s24*s35*s43*s52)-(s44*s55*s23*s32);
            int d21 =(s21*s33*s44*s55)+(s41*s53*s24*s35)+(s25*s34*s43*s51)+(s45*s54*s23*s31)-
            (s31*s43*s54*s25)-(s51*s23*s34*s45)-(s35*s44*s53*s21)-(s55*s24*s33*s41);
            int d22 =(s31*s44*s53*s25)+(s51*s24*s33*s45)+(s35*s43*s54*s21)+(s55*s23*s34*s41)-
            (s21*s34*s43*s55)-(s41*s54*s23*s35)-(s25*s33*s44*s51)-(s45*s53*s24*s31);
            int d23 =(s31*s43*s55*s24)+(s51*s23*s35*s44)+(s34*s45*s53*s21)+(s54*s25*s33*s41)-
            (s21*s33*s45*s54)-(s41*s53*s25*s34)-(s24*s35*s43*s51)-(s44*s55*s23*s31);
            int d31 =(s21*s32*s44*s55)+(s41*s52*s24*s35)+(s25*s34*s42*s51)+(s45*s54*s22*s31)-
            (s31*s42*s54*s25)-(s51*s22*s34*s45)-(s35*s44*s52*s21)-(s55*s24*s32*s41);
            int d32 =(s31*s44*s52*s25)+(s51*s24*s32*s45)+(s35*s42*s54*s21)+(s55*s22*s34*s41)-
            (s21*s34*s42*s55)-(s41*s54*s22*s35)-(s25*s32*s44*s51)-(s45*s52*s24*s31);
            int d33 =(s31*s42*s55*s24)+(s51*s22*s35*s44)+(s34*s45*s52*s21)+(s54*s25*s32*s41)-
            (s21*s32*s45*s54)-(s41*s52*s25*s34)-(s24*s35*s42*s51)-(s44*s55*s22*s31);
            int d41 =(s21*s32*s43*s55)+(s41*s52*s23*s35)+(s25*s33*s42*s51)+(s45*s53*s22*s31)-
            (s31*s42*s53*s25)-(s51*s22*s33*s45)-(s35*s43*s52*s21)-(s55*s23*s32*s41);
            int d42 =(s31*s43*s52*s25)+(s51*s23*s32*s45)+(s35*s42*s53*s21)+(s55*s22*s33*s41)-
            (s21*s33*s42*s55)-(s41*s53*s22*s35)-(s25*s32*s43*s51)-(s45*s52*s23*s31);
            int d43 =(s31*s42*s55*s23)+(s51*s22*s35*s43)+(s33*s45*s52*s21)+(s53*s25*s32*s41)-
            (s21*s32*s45*s53)-(s41*s52*s25*s33)-(s23*s35*s42*s51)-(s43*s55*s22*s31);
            int d51 =(s21*s32*s43*s54)+(s41*s52*s23*s34)+(s24*s33*s42*s51)+(s44*s53*s22*s31)-
            (s31*s42*s53*s24)-(s51*s22*s33*s44)-(s34*s43*s52*s21)-(s54*s23*s32*s41);
            int d52 =(s31*s43*s52*s24)+(s51*s23*s32*s44)+(s34*s42*s53*s21)+(s54*s22*s33*s41)-
            (s21*s33*s42*s54)-(s41*s53*s22*s34)-(s24*s32*s43*s51)-(s44*s52*s23*s31);
            int d53 =(s31*s42*s54*s23)+(s51*s22*s34*s43)+(s33*s44*s52*s21)+(s53*s24*s32*s41)-
            (s21*s32*s44*s53)-(s41*s52*s24*s33)-(s23*s34*s42*s51)-(s43*s54*s22*s31);
            int detA11sonuc=d11+d12+d13;
            int detA12sonuc=d21+d22+d23;
            int detA13sonuc=d31+d32+d33;
            int detA14sonuc=d41+d42+d43;
            int detA15sonuc=d51+d52+d53;
            int anaSonuc = (s11*detA11sonuc)+((-s12)*detA12sonuc)+(s13*detA13sonuc)+((-s14)*detA14sonuc)+(s15*detA15sonuc);
            matrixsonuc.setText(Integer.toString(anaSonuc));
        }
           else if(transpozA.isSelected()==true){
            g1.setText(x11.getText());
            g2.setText(x12.getText());
            g3.setText(x13.getText());
            g4.setText(x14.getText());
            g5.setText(x15.getText());
            g6.setText(y11.getText());
            g7.setText(y12.getText());
            g8.setText(y13.getText());
            g9.setText(y14.getText());
            g10.setText(y15.getText());
            g11.setText(z11.getText());
            g12.setText(z12.getText());
            g13.setText(z13.getText());
            g14.setText(z14.getText());
            g15.setText(z15.getText());
            g16.setText(w11.getText());
            g17.setText(w12.getText());
            g18.setText(w13.getText());
            g19.setText(w14.getText());
            g20.setText(w15.getText());
            g21.setText(q11.getText());
            g22.setText(q12.getText());
            g23.setText(q13.getText());
            g24.setText(q14.getText());
            g25.setText(q15.getText());
            
        }
            else if(transpozB.isSelected()==true){
            g1.setText(a11.getText());
            g2.setText(a12.getText());
            g3.setText(a13.getText());
            g4.setText(a14.getText());
            g5.setText(a15.getText());
            g6.setText(b11.getText());
            g7.setText(b12.getText());
            g8.setText(b13.getText());
            g9.setText(b14.getText());
            g10.setText(b15.getText());
            g11.setText(c11.getText());
            g12.setText(c12.getText());
            g13.setText(c13.getText());
            g14.setText(c14.getText());
            g15.setText(c15.getText());
            g16.setText(d11.getText());
            g17.setText(d12.getText());
            g18.setText(d13.getText());
            g19.setText(d14.getText());
            g20.setText(d15.getText());
            g21.setText(e11.getText());
            g22.setText(e12.getText());
            g23.setText(e13.getText());
            g24.setText(e14.getText());
            g25.setText(e15.getText());
            
        }
             else if(cikarma.isSelected()==true){
             int s1= Integer.parseInt(x11.getText())-Integer.parseInt(a11.getText());
             int s2= Integer.parseInt(x12.getText())-Integer.parseInt(a12.getText());
             int s3= Integer.parseInt(x13.getText())-Integer.parseInt(a13.getText());
             int s4= Integer.parseInt(x14.getText())-Integer.parseInt(a14.getText());
             int s5= Integer.parseInt(x15.getText())-Integer.parseInt(a15.getText());
             int s6= Integer.parseInt(y11.getText())-Integer.parseInt(b11.getText());
             int s7= Integer.parseInt(y12.getText())-Integer.parseInt(b12.getText());
             int s8= Integer.parseInt(y13.getText())-Integer.parseInt(b13.getText());
             int s9= Integer.parseInt(y14.getText())-Integer.parseInt(b14.getText());
             int s10= Integer.parseInt(y15.getText())-Integer.parseInt(b15.getText());
             int s11= Integer.parseInt(z11.getText())-Integer.parseInt(c11.getText());
             int s12= Integer.parseInt(z12.getText())-Integer.parseInt(c12.getText());
             int s13= Integer.parseInt(z13.getText())-Integer.parseInt(c13.getText());
             int s14= Integer.parseInt(z14.getText())-Integer.parseInt(c14.getText());
             int s15= Integer.parseInt(z15.getText())-Integer.parseInt(c15.getText());
             int s16= Integer.parseInt(w11.getText())-Integer.parseInt(d11.getText());
             int s17= Integer.parseInt(w12.getText())-Integer.parseInt(d12.getText());
             int s18= Integer.parseInt(w13.getText())-Integer.parseInt(d13.getText());
             int s19= Integer.parseInt(w14.getText())-Integer.parseInt(d14.getText());
             int s20= Integer.parseInt(w15.getText())-Integer.parseInt(d15.getText());
             int s21= Integer.parseInt(q11.getText())-Integer.parseInt(e11.getText());
             int s22= Integer.parseInt(q12.getText())-Integer.parseInt(e12.getText());
             int s23= Integer.parseInt(q13.getText())-Integer.parseInt(e13.getText());
             int s24= Integer.parseInt(q14.getText())-Integer.parseInt(e14.getText());
             int s25= Integer.parseInt(q15.getText())-Integer.parseInt(e15.getText());
             g1.setText(Integer.toString(s1));
             g6.setText(Integer.toString(s2));
             g11.setText(Integer.toString(s3));
             g16.setText(Integer.toString(s4));
             g21.setText(Integer.toString(s5));
             g2.setText(Integer.toString(s6));
             g7.setText(Integer.toString(s7));
             g12.setText(Integer.toString(s8));
             g17.setText(Integer.toString(s9));
             g22.setText(Integer.toString(s10));
             g3.setText(Integer.toString(s11));
             g8.setText(Integer.toString(s12));
             g13.setText(Integer.toString(s13));
             g18.setText(Integer.toString(s14));
             g23.setText(Integer.toString(s15));
             g4.setText(Integer.toString(s16));
             g9.setText(Integer.toString(s17));
             g14.setText(Integer.toString(s18));
             g19.setText(Integer.toString(s19));
             g24.setText(Integer.toString(s20));
             g5.setText(Integer.toString(s21));
             g10.setText(Integer.toString(s22));
             g15.setText(Integer.toString(s23));
             g20.setText(Integer.toString(s24));
             g25.setText(Integer.toString(s25));
         }
                else if(toplama.isSelected()==true){
             int s1= Integer.parseInt(x11.getText())+Integer.parseInt(a11.getText());
             int s2= Integer.parseInt(x12.getText())+Integer.parseInt(a12.getText());
             int s3= Integer.parseInt(x13.getText())+Integer.parseInt(a13.getText());
             int s4= Integer.parseInt(x14.getText())+Integer.parseInt(a14.getText());
             int s5= Integer.parseInt(x15.getText())+Integer.parseInt(a15.getText());
             int s6= Integer.parseInt(y11.getText())+Integer.parseInt(b11.getText());
             int s7= Integer.parseInt(y12.getText())+Integer.parseInt(b12.getText());
             int s8= Integer.parseInt(y13.getText())+Integer.parseInt(b13.getText());
             int s9= Integer.parseInt(y14.getText())+Integer.parseInt(b14.getText());
             int s10= Integer.parseInt(y15.getText())+Integer.parseInt(b15.getText());
             int s11= Integer.parseInt(z11.getText())+Integer.parseInt(c11.getText());
             int s12= Integer.parseInt(z12.getText())+Integer.parseInt(c12.getText());
             int s13= Integer.parseInt(z13.getText())+Integer.parseInt(c13.getText());
             int s14= Integer.parseInt(z14.getText())+Integer.parseInt(c14.getText());
             int s15= Integer.parseInt(z15.getText())+Integer.parseInt(c15.getText());
             int s16= Integer.parseInt(w11.getText())+Integer.parseInt(d11.getText());
             int s17= Integer.parseInt(w12.getText())+Integer.parseInt(d12.getText());
             int s18= Integer.parseInt(w13.getText())+Integer.parseInt(d13.getText());
             int s19= Integer.parseInt(w14.getText())+Integer.parseInt(d14.getText());
             int s20= Integer.parseInt(w15.getText())+Integer.parseInt(d15.getText());
             int s21= Integer.parseInt(q11.getText())+Integer.parseInt(e11.getText());
             int s22= Integer.parseInt(q12.getText())+Integer.parseInt(e12.getText());
             int s23= Integer.parseInt(q13.getText())+Integer.parseInt(e13.getText());
             int s24= Integer.parseInt(q14.getText())+Integer.parseInt(e14.getText());
             int s25= Integer.parseInt(q15.getText())+Integer.parseInt(e15.getText());
             g1.setText(Integer.toString(s1));
             g6.setText(Integer.toString(s2));
             g11.setText(Integer.toString(s3));
             g16.setText(Integer.toString(s4));
             g21.setText(Integer.toString(s5));
             g2.setText(Integer.toString(s6));
             g7.setText(Integer.toString(s7));
             g12.setText(Integer.toString(s8));
             g17.setText(Integer.toString(s9));
             g22.setText(Integer.toString(s10));
             g3.setText(Integer.toString(s11));
             g8.setText(Integer.toString(s12));
             g13.setText(Integer.toString(s13));
             g18.setText(Integer.toString(s14));
             g23.setText(Integer.toString(s15));
             g4.setText(Integer.toString(s16));
             g9.setText(Integer.toString(s17));
             g14.setText(Integer.toString(s18));
             g19.setText(Integer.toString(s19));
             g24.setText(Integer.toString(s20));
             g5.setText(Integer.toString(s21));
             g10.setText(Integer.toString(s22));
             g15.setText(Integer.toString(s23));
             g20.setText(Integer.toString(s24));
             g25.setText(Integer.toString(s25));
         }
        else{
            JOptionPane.showMessageDialog(this, "Seçiminizi Yapınız !!");
        }
    }//GEN-LAST:event_hesaplaActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
           int cikisKarar = JOptionPane.showConfirmDialog (null, "Çıkış yapmak istiyor musunuz?","UYARIII",JOptionPane.YES_NO_OPTION);
        if(cikisKarar==JOptionPane.YES_OPTION){
        System.exit(0);
          }
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         new uceuc().setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         new dordedort().setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void z13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_z13KeyTyped
          char ch = evt.getKeyChar();
          
       if (( (ch > '9')) && (ch !='\b')) {// bu if sart kontrolünde sadece 0 ile 9 arasinda rakamlarin girilebilecegini belirtiyoruz

            evt.consume();
        }
    }//GEN-LAST:event_z13KeyTyped

    private void temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleActionPerformed
            g1.setText("*");
            g2.setText("*");
            g3.setText("*");
            g4.setText("*");
            g5.setText("*");  
            g6.setText("*");
            g7.setText("*");
            g8.setText("*");
            g9.setText("*");
            g10.setText("*");
            g11.setText("*");
            g12.setText("*");
            g13.setText("*");
            g14.setText("*");
            g15.setText("*");
            g16.setText("*");
            g17.setText("*");
            g18.setText("*");
            g19.setText("*");
            g20.setText("*");
            g21.setText("*");
            g22.setText("*");
            g23.setText("*");
            g24.setText("*");
            g25.setText("*");
            x11.setText("");
            x12.setText("");
            x13.setText("");
            x14.setText("");
            x15.setText("");
            a11.setText("");
            a12.setText("");
            a13.setText("");
            a14.setText("");
            a15.setText("");
            y11.setText("");
            y12.setText("");
            y13.setText("");
            y14.setText("");
            y15.setText("");
            b11.setText("");
            b12.setText("");
            b13.setText("");
            b14.setText("");
            z11.setText("");
            z12.setText("");
            z13.setText("");
            z14.setText("");
            z15.setText("");
            c11.setText("");
            c12.setText("");
            c13.setText("");
            c14.setText("");
            c15.setText("");
            w11.setText("");
            w12.setText("");
            w13.setText("");
            w14.setText("");
            w15.setText("");
            d11.setText("");
            d12.setText("");
            d13.setText("");
            d14.setText("");
            d15.setText("");
            q11.setText("");
            q12.setText("");
            q13.setText("");
            q14.setText("");
            q15.setText("");
            e11.setText("");
            e12.setText("");
            e13.setText("");
            e14.setText("");
            e15.setText("");
    }//GEN-LAST:event_temizleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try{File dosya = new File("besebes.txt");
                    FileWriter fw= new FileWriter(dosya,true);
PrintWriter pw= new PrintWriter(fw);
pw.print(g1.getText()+" ");
pw.print(g6.getText()+" ");
pw.print(g11.getText()+" ");
pw.print(g16.getText()+" ");
pw.println(g21.getText());
pw.print(g2.getText()+" ");
pw.print(g7.getText()+" ");
pw.print(g12.getText()+" ");
pw.print(g17.getText()+" ");
pw.println(g22.getText());
pw.print(g3.getText()+" ");
pw.print(g8.getText()+" ");
pw.print(g13.getText()+" ");
pw.print(g18.getText()+" ");
pw.println(g23.getText());
pw.print(g4.getText()+" ");
pw.print(g9.getText()+" ");
pw.print(g14.getText()+" ");
pw.print(g19.getText()+" ");
pw.println(g24.getText());
pw.print(g5.getText()+" ");
pw.print(g10.getText()+" ");
pw.print(g15.getText()+" ");
pw.print(g20.getText()+" ");
pw.print(g25.getText());
pw.println();
pw.println("Determinant Sonucu :"+matrixsonuc.getText());
pw.println("---------"); 

pw.close();
JOptionPane.showMessageDialog(null, "Kaydedildi!!");
}
catch(IOException e)
{
System.out.println("HATA !!!");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(besebes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(besebes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(besebes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(besebes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new besebes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a11;
    private javax.swing.JTextField a12;
    private javax.swing.JTextField a13;
    private javax.swing.JTextField a14;
    private javax.swing.JTextField a15;
    private javax.swing.JLabel aMatrisi;
    private javax.swing.JTextField b11;
    private javax.swing.JTextField b12;
    private javax.swing.JTextField b13;
    private javax.swing.JTextField b14;
    private javax.swing.JTextField b15;
    private javax.swing.JLabel bMatrisi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField c11;
    private javax.swing.JTextField c12;
    private javax.swing.JTextField c13;
    private javax.swing.JTextField c14;
    private javax.swing.JTextField c15;
    private javax.swing.JRadioButton cikarma;
    private javax.swing.JTextField d11;
    private javax.swing.JTextField d12;
    private javax.swing.JTextField d13;
    private javax.swing.JTextField d14;
    private javax.swing.JTextField d15;
    private javax.swing.JTextField e11;
    private javax.swing.JTextField e12;
    private javax.swing.JTextField e13;
    private javax.swing.JTextField e14;
    private javax.swing.JTextField e15;
    private javax.swing.JLabel g1;
    private javax.swing.JLabel g10;
    private javax.swing.JLabel g11;
    private javax.swing.JLabel g12;
    private javax.swing.JLabel g13;
    private javax.swing.JLabel g14;
    private javax.swing.JLabel g15;
    private javax.swing.JLabel g16;
    private javax.swing.JLabel g17;
    private javax.swing.JLabel g18;
    private javax.swing.JLabel g19;
    private javax.swing.JLabel g2;
    private javax.swing.JLabel g20;
    private javax.swing.JLabel g21;
    private javax.swing.JLabel g22;
    private javax.swing.JLabel g23;
    private javax.swing.JLabel g24;
    private javax.swing.JLabel g25;
    private javax.swing.JLabel g3;
    private javax.swing.JLabel g4;
    private javax.swing.JLabel g5;
    private javax.swing.JLabel g6;
    private javax.swing.JLabel g7;
    private javax.swing.JLabel g8;
    private javax.swing.JLabel g9;
    private javax.swing.JButton hesapla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton matrixA;
    private javax.swing.JRadioButton matrixB;
    private javax.swing.JLabel matrixsonuc;
    private javax.swing.JTextField q11;
    private javax.swing.JTextField q12;
    private javax.swing.JTextField q13;
    private javax.swing.JTextField q14;
    private javax.swing.JTextField q15;
    private javax.swing.JButton temizle;
    private javax.swing.JRadioButton toplama;
    private javax.swing.JRadioButton transpozA;
    private javax.swing.JRadioButton transpozB;
    private javax.swing.JTextField w11;
    private javax.swing.JTextField w12;
    private javax.swing.JTextField w13;
    private javax.swing.JTextField w14;
    private javax.swing.JTextField w15;
    private javax.swing.JTextField x11;
    private javax.swing.JTextField x12;
    private javax.swing.JTextField x13;
    private javax.swing.JTextField x14;
    private javax.swing.JTextField x15;
    private javax.swing.JTextField y11;
    private javax.swing.JTextField y12;
    private javax.swing.JTextField y13;
    private javax.swing.JTextField y14;
    private javax.swing.JTextField y15;
    private javax.swing.JTextField z11;
    private javax.swing.JTextField z12;
    private javax.swing.JTextField z13;
    private javax.swing.JTextField z14;
    private javax.swing.JTextField z15;
    // End of variables declaration//GEN-END:variables

    private void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("matrix.png")));
    }
}
