
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author spook
 */
public class dordedort extends javax.swing.JFrame {

    /**
     * Creates new form dort
     */
    public dordedort() {
        initComponents();
        Seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        x12 = new javax.swing.JTextField();
        x14 = new javax.swing.JTextField();
        x13 = new javax.swing.JTextField();
        y14 = new javax.swing.JTextField();
        y11 = new javax.swing.JTextField();
        matrixA = new javax.swing.JRadioButton();
        y12 = new javax.swing.JTextField();
        hesapla = new javax.swing.JButton();
        y13 = new javax.swing.JTextField();
        z11 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        w11 = new javax.swing.JTextField();
        aMatrisi = new javax.swing.JLabel();
        w12 = new javax.swing.JTextField();
        z12 = new javax.swing.JTextField();
        w13 = new javax.swing.JTextField();
        z13 = new javax.swing.JTextField();
        w14 = new javax.swing.JTextField();
        x11 = new javax.swing.JTextField();
        z14 = new javax.swing.JTextField();
        matrixsonuc = new javax.swing.JLabel();
        c11 = new javax.swing.JTextField();
        d11 = new javax.swing.JTextField();
        aMatrisi1 = new javax.swing.JLabel();
        d12 = new javax.swing.JTextField();
        c12 = new javax.swing.JTextField();
        d13 = new javax.swing.JTextField();
        c13 = new javax.swing.JTextField();
        d14 = new javax.swing.JTextField();
        a12 = new javax.swing.JTextField();
        a14 = new javax.swing.JTextField();
        a13 = new javax.swing.JTextField();
        b14 = new javax.swing.JTextField();
        b11 = new javax.swing.JTextField();
        b12 = new javax.swing.JTextField();
        a11 = new javax.swing.JTextField();
        b13 = new javax.swing.JTextField();
        c14 = new javax.swing.JTextField();
        matrixB = new javax.swing.JRadioButton();
        g1 = new javax.swing.JLabel();
        g2 = new javax.swing.JLabel();
        g3 = new javax.swing.JLabel();
        g5 = new javax.swing.JLabel();
        g6 = new javax.swing.JLabel();
        g7 = new javax.swing.JLabel();
        g9 = new javax.swing.JLabel();
        g10 = new javax.swing.JLabel();
        g11 = new javax.swing.JLabel();
        temizle = new javax.swing.JButton();
        transpozA = new javax.swing.JRadioButton();
        transpozB = new javax.swing.JRadioButton();
        g4 = new javax.swing.JLabel();
        g8 = new javax.swing.JLabel();
        g12 = new javax.swing.JLabel();
        g13 = new javax.swing.JLabel();
        g14 = new javax.swing.JLabel();
        g15 = new javax.swing.JLabel();
        g16 = new javax.swing.JLabel();
        cikarma = new javax.swing.JRadioButton();
        toplama = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("4x4 Matrix Hesaplama");

        x12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        x14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        x13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        y14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        y11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        buttonGroup1.add(matrixA);
        matrixA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        matrixA.setText("A Determinant");

        y12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        hesapla.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hesapla.setText("Hesapla");
        hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesaplaActionPerformed(evt);
            }
        });

        y13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        z11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Det Sonucu: ");

        w11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        aMatrisi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aMatrisi.setText("A Matrisi");

        w12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        z12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        w13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        z13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        w14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        x11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        z14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        c11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        d11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        aMatrisi1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aMatrisi1.setText("B Matrisi");

        d12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        c12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        d13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        c13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        d14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        a12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        a14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        a13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        b14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        b11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        b12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        a11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        b13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        c14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a14KeyTyped(evt);
            }
        });

        buttonGroup1.add(matrixB);
        matrixB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        matrixB.setText("B Determinant");

        g1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g1.setText("*");

        g2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g2.setText("*");

        g3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g3.setText("*");

        g5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g5.setText("*");

        g6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g6.setText("*");

        g7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g7.setText("*");

        g9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g9.setText("*");

        g10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g10.setText("*");

        g11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g11.setText("*");

        temizle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        temizle.setText("Temizle");
        temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleActionPerformed(evt);
            }
        });

        buttonGroup1.add(transpozA);
        transpozA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transpozA.setText("A Transpoz ");
        transpozA.setVerifyInputWhenFocusTarget(false);

        buttonGroup1.add(transpozB);
        transpozB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transpozB.setText("B Transpoz ");
        transpozB.setVerifyInputWhenFocusTarget(false);

        g4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g4.setText("*");

        g8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g8.setText("*");

        g12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g12.setText("*");

        g13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g13.setText("*");

        g14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g14.setText("*");

        g15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g15.setText("*");

        g16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g16.setText("*");

        buttonGroup1.add(cikarma);
        cikarma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cikarma.setText("A - B işlemi");
        cikarma.setVerifyInputWhenFocusTarget(false);

        buttonGroup1.add(toplama);
        toplama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        toplama.setText("A + B işlemi");
        toplama.setVerifyInputWhenFocusTarget(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Matris Sonuç:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Kaydet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Matris Hesaplama");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("3x3 Matris Hesaplama");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("5x5 Matris Hesaplama");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Çıkış");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(aMatrisi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(w11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(w12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(w13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(y11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(y12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(y13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(z11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(z12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(z13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(x11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(x12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(x13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(w14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(y14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(z14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(x14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(aMatrisi1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matrixA)
                            .addComponent(matrixB)
                            .addComponent(transpozA)
                            .addComponent(cikarma)
                            .addComponent(transpozB)
                            .addComponent(toplama))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(c12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(c13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(a11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(a13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(d11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(d14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(b14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(c14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(321, 321, 321))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(hesapla)
                        .addGap(18, 18, 18)
                        .addComponent(temizle)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrixsonuc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g1)
                                .addGap(18, 18, 18)
                                .addComponent(g5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g2)
                                .addGap(18, 18, 18)
                                .addComponent(g6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g3)
                                .addGap(18, 18, 18)
                                .addComponent(g7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g4)
                                .addGap(18, 18, 18)
                                .addComponent(g8)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(g9)
                            .addComponent(g10)
                            .addComponent(g11)
                            .addComponent(g12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(g13)
                            .addComponent(g14)
                            .addComponent(g15)
                            .addComponent(g16))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aMatrisi)
                    .addComponent(matrixA)
                    .addComponent(aMatrisi1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(x11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(x12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(x13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(y11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(z11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(z13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(z12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(w11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(w13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(w12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(x14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(z14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(w14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(a11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(d11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(a14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(matrixB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transpozA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transpozB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cikarma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toplama)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(g1)
                            .addComponent(g5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(g6)
                            .addComponent(g2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(g3)
                            .addComponent(g7))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(g4)
                            .addComponent(g8)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(g9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g11)
                        .addGap(1, 1, 1)
                        .addComponent(g12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(g13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g15)
                        .addGap(1, 1, 1)
                        .addComponent(g16)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(matrixsonuc)
                            .addGap(9, 9, 9))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButton1)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(temizle)
                        .addComponent(hesapla)))
                .addGap(13, 13, 13))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesaplaActionPerformed
        if(matrixA.isSelected()==true){
            int sonuc1 = Integer.parseInt(x11.getText());
            int sonuc2 = Integer.parseInt(x12.getText());
            int sonuc3 = Integer.parseInt(x13.getText());
            int sonuc4 = Integer.parseInt(x14.getText());
            int sonuc5 = Integer.parseInt(y11.getText());
            int sonuc6 = Integer.parseInt(y12.getText());
            int sonuc7 = Integer.parseInt(y13.getText());
            int sonuc8 = Integer.parseInt(y14.getText());
            int sonuc9 = Integer.parseInt(z11.getText());
            int sonuc10 = Integer.parseInt(z12.getText());
            int sonuc11 = Integer.parseInt(z13.getText());
            int sonuc12 = Integer.parseInt(z14.getText());
            int sonuc13 = Integer.parseInt(w11.getText());
            int sonuc14 = Integer.parseInt(w12.getText());
            int sonuc15 = Integer.parseInt(w13.getText());
            int sonuc16 = Integer.parseInt(w14.getText());
            int d1 =(sonuc1*sonuc6*sonuc11*sonuc16)+(sonuc9*sonuc14*sonuc3*sonuc8)+(sonuc4*sonuc7*sonuc10*sonuc13)+(sonuc12*sonuc15*sonuc2*sonuc5)-
            (sonuc5*sonuc10*sonuc15*sonuc4)-(sonuc13*sonuc2*sonuc7*sonuc12)-(sonuc8*sonuc11*sonuc14*sonuc1)-(sonuc16*sonuc3*sonuc6*sonuc9);
            int d2 =(sonuc5*sonuc11*sonuc14*sonuc4)+(sonuc13*sonuc3*sonuc6*sonuc12)+(sonuc8*sonuc10*sonuc15*sonuc1)+(sonuc16*sonuc2*sonuc7*sonuc9)-
            (sonuc1*sonuc7*sonuc10*sonuc16)-(sonuc9*sonuc15*sonuc2*sonuc8)-(sonuc4*sonuc6*sonuc11*sonuc13)-(sonuc12*sonuc14*sonuc3*sonuc5);
            int d3 =(sonuc5*sonuc10*sonuc16*sonuc3)+(sonuc13*sonuc2*sonuc8*sonuc11)+(sonuc7*sonuc12*sonuc14*sonuc1)+(sonuc15*sonuc4*sonuc6*sonuc9)-
            (sonuc1*sonuc6*sonuc12*sonuc15)-(sonuc9*sonuc14*sonuc4*sonuc7)-(sonuc3*sonuc8*sonuc10*sonuc13)-(sonuc11*sonuc16*sonuc2*sonuc5);
            int detAsonuc=d1+d2+d3;
            matrixsonuc.setText(Integer.toString(detAsonuc));
        }
        else if(matrixB.isSelected()==true){
            int sonuc1 = Integer.parseInt(a11.getText());
            int sonuc2 = Integer.parseInt(a12.getText());
            int sonuc3 = Integer.parseInt(a13.getText());
            int sonuc4 = Integer.parseInt(a14.getText());
            int sonuc5 = Integer.parseInt(b11.getText());
            int sonuc6 = Integer.parseInt(b12.getText());
            int sonuc7 = Integer.parseInt(b13.getText());
            int sonuc8 = Integer.parseInt(b14.getText());
            int sonuc9 = Integer.parseInt(c11.getText());
            int sonuc10 = Integer.parseInt(c12.getText());
            int sonuc11 = Integer.parseInt(c13.getText());
            int sonuc12 = Integer.parseInt(c14.getText());
            int sonuc13 = Integer.parseInt(d11.getText());
            int sonuc14 = Integer.parseInt(d12.getText());
            int sonuc15 = Integer.parseInt(d13.getText());
            int sonuc16 = Integer.parseInt(d14.getText());
            int d1 =(sonuc1*sonuc6*sonuc11*sonuc16)+(sonuc9*sonuc14*sonuc3*sonuc8)+(sonuc4*sonuc7*sonuc10*sonuc13)+(sonuc12*sonuc15*sonuc2*sonuc5)-
            (sonuc5*sonuc10*sonuc15*sonuc4)-(sonuc13*sonuc2*sonuc7*sonuc12)-(sonuc8*sonuc11*sonuc14*sonuc1)-(sonuc16*sonuc3*sonuc6*sonuc9);
            int d2 =(sonuc5*sonuc11*sonuc14*sonuc4)+(sonuc13*sonuc3*sonuc6*sonuc12)+(sonuc8*sonuc10*sonuc15*sonuc1)+(sonuc16*sonuc2*sonuc7*sonuc9)-
            (sonuc1*sonuc7*sonuc10*sonuc16)-(sonuc9*sonuc15*sonuc2*sonuc8)-(sonuc4*sonuc6*sonuc11*sonuc13)-(sonuc12*sonuc14*sonuc3*sonuc5);
            int d3 =(sonuc5*sonuc10*sonuc16*sonuc3)+(sonuc13*sonuc2*sonuc8*sonuc11)+(sonuc7*sonuc12*sonuc14*sonuc1)+(sonuc15*sonuc4*sonuc6*sonuc9)-
            (sonuc1*sonuc6*sonuc12*sonuc15)-(sonuc9*sonuc14*sonuc4*sonuc7)-(sonuc3*sonuc8*sonuc10*sonuc13)-(sonuc11*sonuc16*sonuc2*sonuc5);
            int detAsonuc=d1+d2+d3;
            matrixsonuc.setText(Integer.toString(detAsonuc));
        }
        else if(transpozA.isSelected()==true){
            g1.setText(x11.getText());
            g2.setText(x12.getText());
            g3.setText(x13.getText());
            g4.setText(x14.getText());
            g5.setText(y11.getText());
            g6.setText(y12.getText());
            g7.setText(y13.getText());
            g8.setText(y14.getText());
            g9.setText(z11.getText());
            g10.setText(z12.getText());
            g11.setText(z13.getText());
            g12.setText(z14.getText());
            g13.setText(w11.getText());
            g14.setText(w12.getText());
            g15.setText(w13.getText());
            g16.setText(w14.getText());
            
        }
         else if(transpozB.isSelected()==true){
            g1.setText(a11.getText());
            g2.setText(a12.getText());
            g3.setText(a13.getText());
            g4.setText(a14.getText());
            g5.setText(b11.getText());
            g6.setText(b12.getText());
            g7.setText(b13.getText());
            g8.setText(b14.getText());
            g9.setText(b11.getText());
            g10.setText(c12.getText());
            g11.setText(c13.getText());
            g12.setText(c14.getText());
            g13.setText(d11.getText());
            g14.setText(d12.getText());
            g15.setText(d13.getText());
            g16.setText(d14.getText());
            
        }
         else if(cikarma.isSelected()==true){
             int s1= Integer.parseInt(x11.getText())-Integer.parseInt(a11.getText());
             int s2= Integer.parseInt(x12.getText())-Integer.parseInt(a12.getText());
             int s3= Integer.parseInt(x13.getText())-Integer.parseInt(a13.getText());
             int s4= Integer.parseInt(x14.getText())-Integer.parseInt(a14.getText());
             int s5= Integer.parseInt(y11.getText())-Integer.parseInt(b11.getText());
             int s6= Integer.parseInt(y12.getText())-Integer.parseInt(b12.getText());
             int s7= Integer.parseInt(y13.getText())-Integer.parseInt(b13.getText());
             int s8= Integer.parseInt(y14.getText())-Integer.parseInt(b14.getText());
             int s9= Integer.parseInt(z11.getText())-Integer.parseInt(c11.getText());
             int s10= Integer.parseInt(z12.getText())-Integer.parseInt(c12.getText());
             int s11= Integer.parseInt(z13.getText())-Integer.parseInt(c13.getText());
             int s12= Integer.parseInt(z14.getText())-Integer.parseInt(c14.getText());
             int s13= Integer.parseInt(w11.getText())-Integer.parseInt(d11.getText());
             int s14= Integer.parseInt(w12.getText())-Integer.parseInt(d12.getText());
             int s15= Integer.parseInt(w13.getText())-Integer.parseInt(d13.getText());
             int s16= Integer.parseInt(w14.getText())-Integer.parseInt(d14.getText());
             g1.setText(Integer.toString(s1));
             g5.setText(Integer.toString(s2));
             g9.setText(Integer.toString(s3));
             g13.setText(Integer.toString(s4));
             g2.setText(Integer.toString(s5));
             g6.setText(Integer.toString(s6));
             g10.setText(Integer.toString(s7));
             g14.setText(Integer.toString(s8));
             g3.setText(Integer.toString(s9));
             g7.setText(Integer.toString(s10));
             g11.setText(Integer.toString(s11));
             g15.setText(Integer.toString(s12));
             g4.setText(Integer.toString(s13));
             g8.setText(Integer.toString(s14));
             g12.setText(Integer.toString(s15));
             g16.setText(Integer.toString(s16));
         }
         else if(toplama.isSelected()==true){
             int s1= Integer.parseInt(x11.getText())+Integer.parseInt(a11.getText());
             int s2= Integer.parseInt(x12.getText())+Integer.parseInt(a12.getText());
             int s3= Integer.parseInt(x13.getText())+Integer.parseInt(a13.getText());
             int s4= Integer.parseInt(x14.getText())+Integer.parseInt(a14.getText());
             int s5= Integer.parseInt(y11.getText())+Integer.parseInt(b11.getText());
             int s6= Integer.parseInt(y12.getText())+Integer.parseInt(b12.getText());
             int s7= Integer.parseInt(y13.getText())+Integer.parseInt(b13.getText());
             int s8= Integer.parseInt(y14.getText())+Integer.parseInt(b14.getText());
             int s9= Integer.parseInt(z11.getText())+Integer.parseInt(c11.getText());
             int s10= Integer.parseInt(z12.getText())+Integer.parseInt(c12.getText());
             int s11= Integer.parseInt(z13.getText())+Integer.parseInt(c13.getText());
             int s12= Integer.parseInt(z14.getText())+Integer.parseInt(c14.getText());
             int s13= Integer.parseInt(w11.getText())+Integer.parseInt(d11.getText());
             int s14= Integer.parseInt(w12.getText())+Integer.parseInt(d12.getText());
             int s15= Integer.parseInt(w13.getText())+Integer.parseInt(d13.getText());
             int s16= Integer.parseInt(w14.getText())+Integer.parseInt(d14.getText());
             g1.setText(Integer.toString(s1));
             g5.setText(Integer.toString(s2));
             g9.setText(Integer.toString(s3));
             g13.setText(Integer.toString(s4));
             g2.setText(Integer.toString(s5));
             g6.setText(Integer.toString(s6));
             g10.setText(Integer.toString(s7));
             g14.setText(Integer.toString(s8));
             g3.setText(Integer.toString(s9));
             g7.setText(Integer.toString(s10));
             g11.setText(Integer.toString(s11));
             g15.setText(Integer.toString(s12));
             g4.setText(Integer.toString(s13));
             g8.setText(Integer.toString(s14));
             g12.setText(Integer.toString(s15));
             g16.setText(Integer.toString(s16));
         }
        else{
            JOptionPane.showMessageDialog(this, "Seçiminizi Yapınız !!");
        }
        
    }//GEN-LAST:event_hesaplaActionPerformed

    private void temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleActionPerformed

            g1.setText("*");
            g2.setText("*");
            g3.setText("*");
            g4.setText("*");
            g5.setText("*");  
            g6.setText("*");
            g7.setText("*");
            g8.setText("*");
            g9.setText("*");
            g10.setText("*");
            g11.setText("*");
            g12.setText("*");
            g13.setText("*");
            g14.setText("*");
            g15.setText("*");
            g16.setText("*");
            x11.setText("");
            x12.setText("");
            x13.setText("");
            x14.setText("");
            a11.setText("");
            a12.setText("");
            a13.setText("");
            a14.setText("");
            y11.setText("");
            y12.setText("");
            y13.setText("");
            y14.setText("");
            b11.setText("");
            b12.setText("");
            b13.setText("");
            b14.setText("");
            z11.setText("");
            z12.setText("");
            z13.setText("");
            z14.setText("");
            c11.setText("");
            c12.setText("");
            c13.setText("");
            c14.setText("");
            w11.setText("");
            w12.setText("");
            w13.setText("");
            w14.setText("");
            d11.setText("");
            d12.setText("");
            d13.setText("");
            d14.setText("");

    }//GEN-LAST:event_temizleActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
         int cikisKarar = JOptionPane.showConfirmDialog (null, "Çıkış yapmak istiyor musunuz?","UYARIII",JOptionPane.YES_NO_OPTION);
        if(cikisKarar==JOptionPane.YES_OPTION){
        System.exit(0);
          }
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new besebes().setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         new uceuc().setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void a14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a14KeyTyped
          char ch = evt.getKeyChar();
       if (( (ch > '9')) && (ch !='\b')) {// bu if sart kontrolünde sadece 0 ile 9 arasinda rakamlarin girilebilecegini belirtiyoruz

            evt.consume();
        }
    }//GEN-LAST:event_a14KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

                        try{File dosya = new File("dordedort.txt");
                    FileWriter fw= new FileWriter(dosya,true);
PrintWriter pw= new PrintWriter(fw);
pw.print(g1.getText()+" ");
pw.print(g5.getText()+" ");
pw.print(g9.getText()+" ");
pw.println(g13.getText());
pw.print(g2.getText()+" ");
pw.print(g6.getText()+" ");
pw.print(g10.getText()+" ");
pw.println(g14.getText());
pw.print(g3.getText()+" ");
pw.print(g7.getText()+" ");
pw.print(g11.getText()+" ");
pw.println(g15.getText());
pw.print(g4.getText()+" ");
pw.print(g8.getText()+" ");
pw.print(g12.getText()+" ");
pw.print(g16.getText());
pw.println();
pw.println("Determinant Sonucu :"+matrixsonuc.getText());
pw.println("-------"); 
pw.close();
JOptionPane.showMessageDialog(null, "Kaydedildi!!");
}
catch(IOException e)
{
System.out.println("HATA !!!");
}



    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dordedort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dordedort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dordedort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dordedort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dordedort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a11;
    private javax.swing.JTextField a12;
    private javax.swing.JTextField a13;
    private javax.swing.JTextField a14;
    private javax.swing.JLabel aMatrisi;
    private javax.swing.JLabel aMatrisi1;
    private javax.swing.JTextField b11;
    private javax.swing.JTextField b12;
    private javax.swing.JTextField b13;
    private javax.swing.JTextField b14;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField c11;
    private javax.swing.JTextField c12;
    private javax.swing.JTextField c13;
    private javax.swing.JTextField c14;
    private javax.swing.JRadioButton cikarma;
    private javax.swing.JTextField d11;
    private javax.swing.JTextField d12;
    private javax.swing.JTextField d13;
    private javax.swing.JTextField d14;
    private javax.swing.JLabel g1;
    private javax.swing.JLabel g10;
    private javax.swing.JLabel g11;
    private javax.swing.JLabel g12;
    private javax.swing.JLabel g13;
    private javax.swing.JLabel g14;
    private javax.swing.JLabel g15;
    private javax.swing.JLabel g16;
    private javax.swing.JLabel g2;
    private javax.swing.JLabel g3;
    private javax.swing.JLabel g4;
    private javax.swing.JLabel g5;
    private javax.swing.JLabel g6;
    private javax.swing.JLabel g7;
    private javax.swing.JLabel g8;
    private javax.swing.JLabel g9;
    private javax.swing.JButton hesapla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton matrixA;
    private javax.swing.JRadioButton matrixB;
    private javax.swing.JLabel matrixsonuc;
    private javax.swing.JButton temizle;
    private javax.swing.JRadioButton toplama;
    private javax.swing.JRadioButton transpozA;
    private javax.swing.JRadioButton transpozB;
    private javax.swing.JTextField w11;
    private javax.swing.JTextField w12;
    private javax.swing.JTextField w13;
    private javax.swing.JTextField w14;
    private javax.swing.JTextField x11;
    private javax.swing.JTextField x12;
    private javax.swing.JTextField x13;
    private javax.swing.JTextField x14;
    private javax.swing.JTextField y11;
    private javax.swing.JTextField y12;
    private javax.swing.JTextField y13;
    private javax.swing.JTextField y14;
    private javax.swing.JTextField z11;
    private javax.swing.JTextField z12;
    private javax.swing.JTextField z13;
    private javax.swing.JTextField z14;
    // End of variables declaration//GEN-END:variables

    private void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("matrix.png")));
    }
}
