
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author spook
 */
public class uceuc extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public uceuc() {

        initComponents();
        Seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        hesapla = new javax.swing.JButton();
        x11 = new javax.swing.JTextField();
        x12 = new javax.swing.JTextField();
        x13 = new javax.swing.JTextField();
        y11 = new javax.swing.JTextField();
        y12 = new javax.swing.JTextField();
        y13 = new javax.swing.JTextField();
        z11 = new javax.swing.JTextField();
        z12 = new javax.swing.JTextField();
        z13 = new javax.swing.JTextField();
        a11 = new javax.swing.JLabel();
        a12 = new javax.swing.JLabel();
        a13 = new javax.swing.JLabel();
        a14 = new javax.swing.JLabel();
        a15 = new javax.swing.JLabel();
        a16 = new javax.swing.JLabel();
        a17 = new javax.swing.JLabel();
        a18 = new javax.swing.JLabel();
        a19 = new javax.swing.JLabel();
        transpozA = new javax.swing.JRadioButton();
        x14 = new javax.swing.JTextField();
        x15 = new javax.swing.JTextField();
        x16 = new javax.swing.JTextField();
        y14 = new javax.swing.JTextField();
        y15 = new javax.swing.JTextField();
        y16 = new javax.swing.JTextField();
        z14 = new javax.swing.JTextField();
        z15 = new javax.swing.JTextField();
        z16 = new javax.swing.JTextField();
        aMatrisi = new javax.swing.JLabel();
        bMatrisi = new javax.swing.JLabel();
        cikarma = new javax.swing.JRadioButton();
        toplama = new javax.swing.JRadioButton();
        matrixA = new javax.swing.JRadioButton();
        matrixB = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        matrixsonuc = new javax.swing.JLabel();
        transpozB = new javax.swing.JRadioButton();
        temizle = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("3x3 Matrix Hesaplama");
        setFocusCycleRoot(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        hesapla.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hesapla.setText("Hesapla");
        hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesaplaActionPerformed(evt);
            }
        });

        x11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                x11FocusLost(evt);
            }
        });
        x11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                x11KeyTyped(evt);
            }
        });

        x12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                x13FocusLost(evt);
            }
        });
        x12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        x13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                x13FocusLost(evt);
            }
        });
        x13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        y11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                x13FocusLost(evt);
            }
        });
        y11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        y12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                x13FocusLost(evt);
            }
        });
        y12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        y13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                x13FocusLost(evt);
            }
        });
        y13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        z11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                x13FocusLost(evt);
            }
        });
        z11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        z12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                x13FocusLost(evt);
            }
        });
        z12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        z13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                x13FocusLost(evt);
            }
        });
        z13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        a11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a11.setText("*");

        a12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a12.setText("*");

        a13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a13.setText("*");

        a14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a14.setText("*");

        a15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a15.setText("*");

        a16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a16.setText("*");

        a17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a17.setText("*");

        a18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a18.setText("*");

        a19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a19.setText("*");

        buttonGroup1.add(transpozA);
        transpozA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transpozA.setText("A Transpoz ");
        transpozA.setVerifyInputWhenFocusTarget(false);

        x14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        x15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        x16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        y14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        y15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        y16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        z14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        z15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        z16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                y11KeyTyped(evt);
            }
        });

        aMatrisi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aMatrisi.setText("A Matrisi");

        bMatrisi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bMatrisi.setText("B Matrisi");

        buttonGroup1.add(cikarma);
        cikarma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cikarma.setText("A - B işlemi");
        cikarma.setVerifyInputWhenFocusTarget(false);

        buttonGroup1.add(toplama);
        toplama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        toplama.setText("A + B işlemi");

        buttonGroup1.add(matrixA);
        matrixA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        matrixA.setText("A Determinant");

        buttonGroup1.add(matrixB);
        matrixB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        matrixB.setText("B  Determinant");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Det Sonucu : ");

        matrixsonuc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        buttonGroup1.add(transpozB);
        transpozB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transpozB.setText("B Transpoz");

        temizle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        temizle.setText("Temizle");
        temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Matris Sonuç:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Kaydet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Matris Hesaplama");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jMenuItem1.setText("4x4 Matris Hesaplama");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jMenuItem2.setText("5x5 Matris Hesaplama");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Çıkış");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hesapla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temizle)
                .addGap(23, 23, 23)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(matrixsonuc)
                .addGap(125, 125, 125))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a19))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(a11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(a12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(a13))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(a14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(a15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(a16))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aMatrisi)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(x11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(x12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(x13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(y11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(y12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(y13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(z11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(z12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(z13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bMatrisi)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(y14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(z14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(y15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(y16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(z15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(z16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(x14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(x15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(x16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cikarma)
                    .addComponent(transpozA)
                    .addComponent(toplama)
                    .addComponent(transpozB)
                    .addComponent(matrixA)
                    .addComponent(matrixB))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aMatrisi)
                            .addComponent(bMatrisi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(x14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(x15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(x16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(y14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(z14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(z16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(z15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(x11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(x12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(x13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(y11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(z11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(z13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(z12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(matrixA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrixB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transpozA)
                        .addGap(3, 3, 3)
                        .addComponent(transpozB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cikarma)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toplama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hesapla)
                            .addComponent(temizle)
                            .addComponent(jLabel1)
                            .addComponent(matrixsonuc)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a11)
                            .addComponent(a13)
                            .addComponent(a12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a14)
                            .addComponent(a16)
                            .addComponent(a15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a17)
                            .addComponent(a19)
                            .addComponent(a18))
                        .addGap(63, 63, 63)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesaplaActionPerformed
      
          if(transpozA.isSelected()==true){
              
              a11.setText(x11.getText());
              a12.setText(y11.getText());
              a13.setText(z11.getText());
              a14.setText(x12.getText());
              a15.setText(y12.getText());
              a16.setText(z12.getText());
              a17.setText(x13.getText());
              a18.setText(y13.getText());
              a19.setText(z13.getText());
              
          }
          else if(cikarma.isSelected()==true){
              
              int sonuc1= Integer.parseInt(x11.getText())-Integer.parseInt(x14.getText());
              int sonuc2= Integer.parseInt(x12.getText())-Integer.parseInt(x15.getText());
              int sonuc3= Integer.parseInt(x13.getText())-Integer.parseInt(x16.getText());
              int sonuc4= Integer.parseInt(y11.getText())-Integer.parseInt(y14.getText());
              int sonuc5= Integer.parseInt(y12.getText())-Integer.parseInt(y15.getText());
              int sonuc6= Integer.parseInt(y13.getText())-Integer.parseInt(y16.getText());
              int sonuc7= Integer.parseInt(z11.getText())-Integer.parseInt(z14.getText());
              int sonuc8= Integer.parseInt(z12.getText())-Integer.parseInt(z15.getText());
              int sonuc9= Integer.parseInt(z13.getText())-Integer.parseInt(z16.getText());
              a11.setText(Integer.toString(sonuc1));
              a12.setText(Integer.toString(sonuc2));
              a13.setText(Integer.toString(sonuc3));
              a14.setText(Integer.toString(sonuc4));
              a15.setText(Integer.toString(sonuc5));
              a16.setText(Integer.toString(sonuc6));
              a17.setText(Integer.toString(sonuc7));
              a18.setText(Integer.toString(sonuc8));
              a19.setText(Integer.toString(sonuc9));
              }  
          
          else if(toplama.isSelected()==true){
               

              int sonuc1= Integer.parseInt(x11.getText())+Integer.parseInt(x14.getText());
              int sonuc2= Integer.parseInt(x12.getText())+Integer.parseInt(x15.getText());
              int sonuc3= Integer.parseInt(x13.getText())+Integer.parseInt(x16.getText());
              int sonuc4= Integer.parseInt(y11.getText())+Integer.parseInt(y14.getText());
              int sonuc5= Integer.parseInt(y12.getText())+Integer.parseInt(y15.getText());
              int sonuc6= Integer.parseInt(y13.getText())+Integer.parseInt(y16.getText());
              int sonuc7= Integer.parseInt(z11.getText())+Integer.parseInt(z14.getText());
              int sonuc8= Integer.parseInt(z12.getText())+Integer.parseInt(z15.getText());
              int sonuc9= Integer.parseInt(z13.getText())+Integer.parseInt(z16.getText());
              a11.setText(Integer.toString(sonuc1));
              a12.setText(Integer.toString(sonuc2));
              a13.setText(Integer.toString(sonuc3));
              a14.setText(Integer.toString(sonuc4));
              a15.setText(Integer.toString(sonuc5));
              a16.setText(Integer.toString(sonuc6));
              a17.setText(Integer.toString(sonuc7));
              a18.setText(Integer.toString(sonuc8));
              a19.setText(Integer.toString(sonuc9));
                      }
          
          else if(transpozB.isSelected()==true){
              a11.setText(x14.getText());
              a12.setText(y14.getText());
              a13.setText(z14.getText());
              a14.setText(x15.getText());
              a15.setText(y15.getText());
              a16.setText(z15.getText());
              a17.setText(x16.getText());
              a18.setText(y16.getText());
              a19.setText(z16.getText());
              
          }
          else if(matrixA.isSelected()==true){

              int sonuc1 = Integer.parseInt(x11.getText());
              int sonuc2 = Integer.parseInt(y12.getText());
              int sonuc3 = Integer.parseInt(z13.getText());
              int sonuc4 = Integer.parseInt(y11.getText());
              int sonuc5 = Integer.parseInt(z12.getText());
              int sonuc6 = Integer.parseInt(x13.getText());
              int sonuc7 = Integer.parseInt(z11.getText());
              int sonuc8 = Integer.parseInt(x12.getText());
              int sonuc9 = Integer.parseInt(y13.getText());
              int detA= ((sonuc1*sonuc2*sonuc3)+(sonuc4*sonuc5*sonuc6)+(sonuc7*sonuc8*sonuc9))-((sonuc6*sonuc2*sonuc7)+(sonuc9*sonuc5*sonuc1)+(sonuc3*sonuc8*sonuc4));
              matrixsonuc.setText(Integer.toString(detA));
          }
          else if(matrixB.isSelected()== true){
              int sonuc1 = Integer.parseInt(x14.getText());
              int sonuc2 = Integer.parseInt(y15.getText());
              int sonuc3 = Integer.parseInt(z16.getText());
              int sonuc4 = Integer.parseInt(y14.getText());
              int sonuc5 = Integer.parseInt(z15.getText());
              int sonuc6 = Integer.parseInt(x16.getText());
              int sonuc7 = Integer.parseInt(z14.getText());
              int sonuc8 = Integer.parseInt(x15.getText());
              int sonuc9 = Integer.parseInt(y16.getText());
              int detA= ((sonuc1*sonuc2*sonuc3)+(sonuc4*sonuc5*sonuc6)+(sonuc7*sonuc8*sonuc9))-((sonuc6*sonuc2*sonuc7)+(sonuc9*sonuc5*sonuc1)+(sonuc3*sonuc8*sonuc4));
              matrixsonuc.setText(Integer.toString(detA));
          }
          else
              JOptionPane.showMessageDialog(this, "Seçiminizi Yapınız !!");
      
             
    }//GEN-LAST:event_hesaplaActionPerformed
    
    private void temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleActionPerformed
            a11.setText("*");
            a12.setText("*");
            a13.setText("*");
            a14.setText("*");
            a15.setText("*");
            a16.setText("*");
            a17.setText("*");
            a18.setText("*");
            a19.setText("*");
            x11.setText("");
            x12.setText("");
            x13.setText("");
            x14.setText("");
            x15.setText("");
            x16.setText("");
            y11.setText("");
            y12.setText("");
            y13.setText("");
            y14.setText("");
            y15.setText("");
            y16.setText("");
            z11.setText("");
            z12.setText("");
            z13.setText("");
            z14.setText("");
            z15.setText("");
            z16.setText("");
    }//GEN-LAST:event_temizleActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
       int cikisKarar = JOptionPane.showConfirmDialog (null, "Çıkış yapmak istiyor musunuz?","UYARIII",JOptionPane.YES_NO_OPTION);
        if(cikisKarar==JOptionPane.YES_OPTION){
        System.exit(0);
          }
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new dordedort().setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new besebes().setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void x11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_x11KeyTyped
          char ch = evt.getKeyChar();
        if (( (ch > '9')) && (ch !='\b')) {

            evt.consume();
        }
    }//GEN-LAST:event_x11KeyTyped

    private void y11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_y11KeyTyped
          char ch = evt.getKeyChar();
        if (( (ch > '9'))&& (ch == '\b')) {

            evt.consume();
        }
    }//GEN-LAST:event_y11KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
                try{
                    File dosya = new File("uceuc.txt");
                    FileWriter fw= new FileWriter(dosya,true);
                    try (PrintWriter pw = new PrintWriter(fw)) {
                        pw.print(a11.getText()+" ");
                        pw.print(a12.getText()+" ");
                        pw.println(a13.getText());
                        pw.print(a14.getText()+" ");
                        pw.print(a15.getText()+" ");
                        pw.println(a16.getText());
                        pw.print(a17.getText()+" ");
                        pw.print(a18.getText()+" ");
                        pw.print(a19.getText());
                        pw.println();
                        pw.println("Determinant Sonucu :"+matrixsonuc.getText());
                        pw.println("-----");
                    }
                    JOptionPane.showMessageDialog(null, "Kaydedildi!!");
        }
                catch(IOException e)
                  {
                   System.out.println("HATA !!!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void x11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_x11FocusLost
   
    }//GEN-LAST:event_x11FocusLost

    private void x13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_x13FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_x13FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new anasayfa().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a11;
    private javax.swing.JLabel a12;
    private javax.swing.JLabel a13;
    private javax.swing.JLabel a14;
    private javax.swing.JLabel a15;
    private javax.swing.JLabel a16;
    private javax.swing.JLabel a17;
    private javax.swing.JLabel a18;
    private javax.swing.JLabel a19;
    private javax.swing.JLabel aMatrisi;
    private javax.swing.JLabel bMatrisi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cikarma;
    private javax.swing.JButton hesapla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton matrixA;
    private javax.swing.JRadioButton matrixB;
    private javax.swing.JLabel matrixsonuc;
    private javax.swing.JButton temizle;
    private javax.swing.JRadioButton toplama;
    private javax.swing.JRadioButton transpozA;
    private javax.swing.JRadioButton transpozB;
    private javax.swing.JTextField x11;
    private javax.swing.JTextField x12;
    private javax.swing.JTextField x13;
    private javax.swing.JTextField x14;
    private javax.swing.JTextField x15;
    private javax.swing.JTextField x16;
    private javax.swing.JTextField y11;
    private javax.swing.JTextField y12;
    private javax.swing.JTextField y13;
    private javax.swing.JTextField y14;
    private javax.swing.JTextField y15;
    private javax.swing.JTextField y16;
    private javax.swing.JTextField z11;
    private javax.swing.JTextField z12;
    private javax.swing.JTextField z13;
    private javax.swing.JTextField z14;
    private javax.swing.JTextField z15;
    private javax.swing.JTextField z16;
    // End of variables declaration//GEN-END:variables

    private void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("matrix.png")));
    }
}
